name: CI
on:
  - push
  - pull_request

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{steps.nvm.outputs.NODE_VERSION }}
      - name: Setup yarn cache
        id: yarncache
        run: echo ::set-output name=dir::$(yarn cache dir)
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarncache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install
      - name: CI
        run: yarn ci
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./temp/coverage/lcov.info
